fastify/fastify-static

index.js
- Minor perf improvements
+ Use strict equality in place of truthiness checks
+ [Check `error` against `undefined`](https://github.com/fastify/fastify-static/compare/master...gj:minor-perf-improvements?expand=1#diff-168726dbe96b3ce427e7fedce31bb0bcR16) instead of relying on the slower `instanceof` operator. Also rename function to mitigate the decrease in self-documentation by moving away from `error instanceof Error`
- Clean up code
+ Rename `checkOptions()` since it's only checking the validity of the root path
+ ~Destructure objects to reduce redundant code~
+ [Improve error message](https://github.com/fastify/fastify-static/compare/master...gj:minor-perf-improvements?expand=1#diff-168726dbe96b3ce427e7fedce31bb0bcR86) for when the `root` option doesn't point to a directory
ETA: Test …
=> Minor improvements (path checking and perf) to module startup

README.md, index.js, package.json, test/static.test.js
Adds support for almost all of the options that [`serve-static`](https://github.com/expressjs/serve-static) supports, which are mostly just options that can be passed to [`send`](https://github.com/pillarjs/send).
=> Support almost all of the same options as serve-static

README.md, index.js, static/403.html, static/404.html, static/500.html, test/static.test.js
Fixes #17 
@mcollina I hope this is what you meant as the solution to #17. Let me know if it isn't. ~~I couldn't find any way to handle 404s with `setNotFoundHandler` so I made it clear in the docs that 404 errors will be passed to Fastify's error handler.~~
=> Forward errors to Fastify instead of sending custom error pages

.travis.yml, example/server-compress.js, index.js, package.json, test/static.test.js
As titled.
The implementation of this is very hacky, and it's needed as `send`  does not play nice with fastify lifecycle. It also introduces some overhead.
Fixes https://github.com/fastify/fastify-static/issues/45.
=> Support compressed assets

README.md, index.js, test/static.test.js
I'm working on a fastify-babel module which will hook `onSend` and run Javascript through babel.  I'm doing this so I can use `npm start` to serve files which can use bare imports such as `import {PolymerElement} from "@polymer/polymer";'.  I have a babel plugin (not yet published) which translates bare imports to be browser compatible.  This babel plugin requires knowledge of the filename being processed so it can properly resolve the import.  I'd like to avoid duplicating codes from fastify-static (either using `send` myself or reimplementing URL to local filename resolution).
=> Expose filename to output stream.

README.md, index.js, test/static.test.js
This option allows fastify-static to be registered without decorating
the reply object.  This is needed when registering multiple static
prefixes to a single route.
Fixes #62
=> Create decorateReply option.

README.md, index.js, test/static.test.js
=> add an option to disable serving

.travis.yml, index.d.ts, package.json, test/types/index.ts, test/types/tsconfig.json
This PR adds the typings from DefinitelyTyped (slightly modified) to the main org repo.
=> feat: add typings

README.md, index.d.ts, index.js, test/static.test.js, test/static/foo.html
This adds an option to redirect requests for directories when the
tailing slash is missing.
Fixes #92
=> feat: Add redirect option

index.js, package.json, test/static.test.js
It is still an error of the root path exists but is not a directory.
Fixes #101
=> Log warning if root directory does not exist instead of throwing error.

index.d.ts, test/types/index.ts
Fix for #114 
I'm not an expert in typescript and declaration files, but i was able to adapt fastify-static declaration file in style of fastify-cookie declaration file (that gives no typescript warnings).
Now it should compile without problems for http2 and htpps too.
Checked on my own server with http, http2 and https settings for server.
=> fix for typescript http2/https warning

README.md, index.js, test/static.test.js
Currently, when fastify-static is configured with `redirect` option set to `false` and a request for a directory does not contain a trailing slash, it causes the server to hang. This is because we only register a directory handler on the underlying `send` stream if `redirect` option is `true`.
This PR updates the library to handle such requests by calling `reply.callNotFound()`. We presume that requesting a directory without using a trailing slash OR setting `redirect` to `true` should be handled explicitly as a 404.
To reproduce the bug:
```js
const path = require('path')
const Fastify = require('fastify')
const fastifyStatic = require('fastify-static')
const fastify = Fastify()
fastify.register(fastifyStatic, {
// using the fixture in fastify-static's test folder
root: …
```
=> fix: handle missing trailing slash on directories

README.md, index.d.ts, index.js, test/static.test.js
For my project the root path is user configurable and can be changed without a server restart, so I needed a way to specify the path dynamically when a file is requested.
This change also allows files to be served from more than one root path
=> Add rootPath overload parameter to sendFile function

README.md, index.js, test/static.test.js
Fastify v3 demands that a promise is returned from a route handler and the promise must not resolve to `undefined`. 
Returning `this` from the `sendFile` method means that the reply thenable can be returned from route handlers to avoid the error log in Fastify v3
=> thenable bugfix

.gitignore, index.js, package.json, test/static.test.js
As reported in https://github.com/fastify/fastify/issues/2616 & https://github.com/fastify/fastify-static/issues/116, the module fails and logs an error when client closes the request prematurely. This PR fixes that by adding a custom `errorHandler` in the  route config so that the specific `ERR_STREAM_PREMATURE_CLOSE` can be handled in a special way. For all other errors, we still fallback to the default `fastify.errorHandler` which was introduced in 3.7.0.
=> fix: prevent premature close error

index.d.ts, test/dir-list.test.js, test/static.test.js, test/static/.example, test/types/index.ts
=> Fix type of dotfiles property

README.md, index.d.ts, index.js, package.json, test/static.test.js, test/types/index.ts
The PR implements similar feature as `res.download` on [Express.js](https://expressjs.com/es/4x/api.html#res.download) on fastify, decorating `reply` object with a `download` function.
Closes [#1563](https://github.com/fastify/fastify/issues/1563)
**Pending**
=> feat: implement download decorator

README.md, index.d.ts, index.js, test/static.test.js
=> Add option to filter files

README.md, index.d.ts, index.js, test/static.test.js, test/types/index.ts
Remove the support of passing string in `wildcard` option and it will throw an error when `wildcard` is not a `boolean`.
It also change the docs to add a new line about `newly added file` for `wildcard` equal to `false`.
Actually, Issue 161 is not a bug and it do not need to be resolve. But this PR is raised from https://github.com/fastify/fastify-static/issues/161#issuecomment-774432298. So, I add it below.
Resolve: #161 
**Note: This is a breaking change.**
=> feat: remove wildcard string support

index.js, test/static.test.js
Just a fix for a bug I found yesterday.
=> Fixed decorator for multiple roots

index.js, test/static.test.js
=> add head routes

index.js, test/static.test.js
Related to #158
When serving a precompressed file, we should derive the `content-type` header from the original extension rather than `.gz` or `.br`.
This PR more or less replicates [what send does internally](https://github.com/pillarjs/send/blob/de073ed3237ade9ff71c61673a34474b30e5d45b/index.js#L833).
=> fix content-type header for precompressed assets

index.js, test/static.test.js
Related to #158
When using the `preCompressed` option, gzip encoded responses should have `Content-Encoding: gzip`  instead of `Content-Encoding: gz`
=> fix content-encoding response header for gzip compression

index.js, test/static.test.js
This closes #218 and #219. The registered `notFoundHandler` wasn't being called when the request path included dotfiles with `send`'s default configuration of ignoring dotfiles. Previous behavior resulted in `fastify` printing an exception and leaving the request hanging.
=> Call 404 handler if requested path is a dotfile

README.md
Witout `index=false` option `fastify-static` will return 404 as it will look for `index.hml` instead returning list of files.
=> fix(docs): list example and index option

index.js, test/static.test.js
It is a quick fix to #246 
Fixes #246 Closes #245
I am think of how to reach the coverage to 100%. Some helps is appreciate.
=> fix: url handle

index.js, test/static.test.js
Related to https://github.com/fastify/fastify-compress/issues/187
=> fix(index): replace all `*` directives with `gzip`

index.js, test/static.test.js
fixes #272 in conjunction  with https://github.com/fastify/fastify-static/pull/271
=> fix: serve directory without trailing slash fixes(#272)

README.md
=> docs(readme): fix dead link to fastify docs

index.d.ts, index.js
* similar to https://github.com/fastify/fastify-cookie/pull/97
=> Add named export to type definitions

index.js, package.json
In this release glob stopped accepting backward slashes on it's patterns, since `path.join` will return backward slashes on windows they have to be replaced by a forward slash which is the posix separator.
I'm not entirely sure about all the implications of this change, specially regarding performance but all the tests seem to be passing and everything should work normally AFAIK since windows accept both backward and forward slashes as path separator.
Closes #281 since glob is already being updated here.
=> fix: update glob to version 8 and fix broken tests

test/static.test.js
This PR fixes a typo.
`precent` -> `percent`
=> chore: fix typo

index.d.ts, test/types/index.ts
* see https://github.com/microsoft/TypeScript/issues/48845
=> make type definitons `"module": "nodenext"` compatible

README.md, index.d.ts, index.js, test/static.test.js, test/types/index.ts
Added request to allowedPath option in order to allow more complex path validation.
Closes #319
=> Added request to allowedPath option

example/server-compress.js, example/server-dir-list.js, example/server.js
=> chore: replace use of deprecated variadic `listen()`

package.json, types/index.d.ts, types/index.test-d.ts
Well fastify-static is an async function and not a callback-function. 
=> move types to types folder and fix typing

README.md, test/static.test.js
=> chore: remove `return` from sync route handlers examples

README.md, index.js, test/static.test.js, types/index.d.ts, types/index.test-d.ts
This pull request adds an optional `constraints` property to the FastifyStaticOptions object that allows users of the library to specify route constraints for any routes that fastify-static registers.
In addition to the above, a small fix for heading levels in README.md is included.
=> feat: allow specifying route constraints

index.js, test/static.test.js
Fixed issue #364 by converting URL object types to a path.
=> fix: convert root parameters with URL object type to a path

README.md
Small documentation change. Spent way too long trying to figure it out, eventually found this message (https://github.com/fastify/fastify-static/issues/354#issuecomment-1386922504) that had the answer. Hopefully this documentation change can help others :smile:
=> Update README with 404+wildcard behavior

.taprc, package.json
Per https://github.com/fastify/fastify-sensible/pull/138#discussion_r1276241298
=> remove linting from the test script

index.js
There is no need to pass the Fastify instance to `setUpHeadAndGet` as it already has access to it
This makes me wonder, for consistency purposes, why not put all the Fastify related functions inside the plugin function to avoid the need to pass `fastify`
=> Remove redundant parameter

README.md, example/server-compress.js, example/server-dir-list.js, example/server-hidden-file.js, example/server.js, index.js, lib/dirList.js, test/content-type.test.js, test/dir-list.test.js, test/static.test.js
See https://github.com/nodejs/node/pull/37246/files#r588397158 and https://nodejs.org/api/modules.html#core-modules
=> perf: use `node:` prefix to bypass require.cache call for builtins

index.js
`request.routeConfig` has been deprecated in Fastify v4.23.0, which causes warnings in fastify-static.
This PR replaces the deprecated api with the recommended `request.routeOptions.config` property.
=> Fix request route config deprecation warnings

index.js
=> fix: allow fallback to fastify@2.22 route config

.eslintrc.json, tsconfig.eslint.json
More information: https://github.com/fastify/fastify-multipart/pull/485
=> fix eslint

index.js, lib/dirList.js
=> refactor: add `u` unicode flag to regex

types/index.d.ts, types/index.test-d.ts
The arguments to the `setHeaders` option is currently `any[]`. This updates those types to be more specific.
=> chore: improve types for `setHeaders` option

index.js, lib/dirList.js, package.json
What changed: glob is stricter in its syntax so we have to escape characters more consistently
Closes: #402
=> Upgrade glob to v10

lib/dirList.js, package.json
`dirList` methods are potentially called on each request to a resource
It had a high number of inline functions that are independent of their scope, which might make it difficult for V8 to optimize them
This PR simply extracts those functions so that they're created once and can be better optimized; it also switches to `fastq` by @mcollina from `p-limit`
=> Optimize `dirList`

index.js, test/static.test.js
It currently does not handle a root with a trailing slash correctly
=> fix: file not found errors when the root has a trailing slash

index.js, test/static.test.js
Fixes #447 
The reason behind we should not use `exposeHeadRoute` is that inside `pumpSendToReply`, we never provide `payload` for `HEAD` route. So, `fastify` think it is providing `empty` response and override the `Content-Length` unexpectedly.
=> fix: wildcard head return content-length header
