index.js, test/static.test.js
=> Fix missing default prefix

index.js, package.json
see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-355972265
=> Updates plugin-meta

index.js, package.json, test/static.test.js
=> Update fastify to 0.42.0.

package.json
=> chore(package): update fastify to version 1.1.1

index.js, test/static.test.js, test/static/foobar.html
Let me know if this is correct, or if adding `/` added some functionality that I am currently not seeing.
=> Do not add / route. Updated dependencies

index.js, test/static.test.js
Fixes #50.
Fixes https://github.com/fastify/help/issues/9.
cc @jinwoo
=> Correctly support 304s

README.md, index.js
Should publish major and branch to `1.x` after this PR is merged
=> Prepare for 1.x branch

README.md, index.js, package.json
~~I wanted to preserve backwards compatibility~~
Closes #77
=> Fix custom not found error for v2

README.md, index.js, package.json, test/static.test.js
Fixes https://github.com/fastify/fastify-static/issues/64.
=> Use glob to avoid setting a wildcard route

README.md
Very funny but this seems more useful. 🤨
=> (Un)intentionally ironic broken link to 404 handler

test/static.test.js
=> maxAge test

README.md, index.d.ts, index.js, test/static.test.js
Allows using the wildcard option to set the globPattern.
ref: https://github.com/fastify/fastify-static/issues/106
=> feat: allow wildcard being globPattern

README.md
Refs: https://github.com/fastify/fastify-static/issues/62
Closes: https://github.com/fastify/fastify-static/issues/120
=> doc: document multiple roots

README.md
this PR fixes a small typo in the readme 
- [x ] run `npm run test` and `npm run benchmark`
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
=> docs: using registered instead of registers

.github/workflows/ci.yml, lib/dirList.js
Fixes #197 and runs CI on windows too
=> fix: failing tests on windows

index.js
=> Avoid a closure

README.md
=> Fix a typo in docs in usage examples of "download" method

.github/workflows/ci.yml, README.md, index.d.ts, index.js, test/static.test.js, test/types/index.ts
=> Add options overload parameter to sendFile function (#238)

test/dir-list.test.js
=> chore: remove unused code

package.json, test/dir-list.test.js, test/static.test.js
=> build(deps-dev): bump standard from 16.0.2 to 17.0.0

.github/workflows/ci.yml, index.js, package.json, test/dir-list.test.js, test/static.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> Update to fastify@4

README.md, index.js, lib/dirList.js, test/dir-list.test.js
=> feat: list option with dotfiles option

index.js
This PR fixes some typos.
- `directoy` -> `directory`
- `shash` -> `slash`
=> chore: fix typo

index.js, package.json
Use @fastify/accept-negotiator instead of encoding-negotiator
=> use @fastify/accept-negotiator

test/static.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> Fix unit tests

package.json
Used in tests but not explicitly defined as dependency:
https://github.com/fastify/fastify-static/blob/fd12dec022adb3a08b6bddb7b635bed8d81689af/test/static.test.js#L14
=> build(deps-dev): add pino

README.md
Fastify requires either absolute paths or pattern matching and so the second GET route definition will trigger errors here.
The example was updated to:
1. Correct the code so it can be copied and pasted to run without errors
2. Add the logger to provide the user feedback on the prompt as they send requests
3. Complete the example with the addition of spinning up the fastify server, otherwise the code just quits.
=> docs: correct example

README.md
=> docs: update the README to state that this plugin support fastify 4

index.js
=> add missing exports for nodenext compatibility

README.md, example/public/.hidden/sample.json, example/server-hidden-file.js, index.js, test/static-hidden/.hidden/sample.json, test/static.test.js, types/index.d.ts
The purpose of this PR is to help with issue #303 
=> feat: allow to serve hidden files

LICENSE
=> chore(license): update license year

index.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
If we are creating both a `HEAD` and `GET` route, calling `.route()` instead of the shorthand is significantly faster.
Fixes https://github.com/fastify/fastify/issues/4533
Here is the rough benchmark script I used:
```js
import Static from './index.js'
import Fastify from 'fastify'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
console.time('fastify warmup')
const fastify = Fastify({
pluginTimeout: 60000
})
fastify.register(Static, {
root: join(dirname(fileURLToPath(import.meta.url)), 'node_modules'),
wildcard: false
})
await fastify.ready()
console.timeEnd('fastify warmup')
```
=> Halve wildcard: false startup time

index.js, package.json, test/static.test.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> Update to @fastify/send v2

types/index.d.ts, types/index.test-d.ts
Types weren't updated after https://github.com/fastify/fastify-static/pull/365
=> add url type

index.js, package.json
Just testing if it'll work on all supported node versions
=> use native stream

index.js, lib/dirList.js
=> refactor: remove unused bindings

index.js
=> perf(index): check set size over converting to array to check length

test/static.test.js
See https://github.com/fastify/fastify-helmet/issues/236
=> test: replace `typeof` undefined check
